version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - curl https://intoli.com/install-google-chrome.sh | bash
      - export CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
      - echo "Chrome version: $CHROME_VERSION"
      - export CHROMEDRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | grep -A 10 "$CHROME_VERSION" | grep "chromedriver-linux64.zip" | grep -o 'https.*zip' | head -1)
      - curl -Lo chromedriver.zip "$CHROMEDRIVER_URL"
      - unzip chromedriver.zip
      - mv chromedriver-linux64/chromedriver /usr/local/bin/
      - chmod +x /usr/local/bin/chromedriver

  pre_build:
    commands:
      - echo "Compilando el proyecto..."
      - mvn compile

  build:
    commands:
      - echo "Ejecutando pruebas con Maven..."
      - mvn test

artifacts:
  files:
    - target/surefire-reports/**
