version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - apt update
      - apt install -y wget unzip curl gnupg2 software-properties-common
      - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
      - apt update
      - apt install -y google-chrome-stable
      - CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
      - DRIVER_VERSION=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | grep -A 10 $CHROME_VERSION | grep "linux64" | grep "chromedriver" | cut -d '"' -f 4)
      - curl -Lo chromedriver.zip "$DRIVER_VERSION"
      - unzip chromedriver.zip
      - mv chromedriver-linux64/chromedriver /usr/local/bin/
      - chmod +x /usr/local/bin/chromedriver
  pre_build:
    commands:
      - mvn compile
  build:
    commands:
      - mvn test
artifacts:
  files:
    - target/surefire-reports/**
